<?php

namespace Controller;
require_once '../vendor/autoload.php';
require_once '../app/Model/Student.php';
require_once '../app/Model/Attendances.php';


use Model\Attendances;
use Model\Student;
use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;

class PDFgeneration extends \Controller
{
    public function generatePDF(): void
    {
        try {
            $userSessions = json_decode($_COOKIE['user_data'], true);
            $userID = $userSessions[0]['user_id']; // Get the first logged-in user
            $attendanceModel = new Attendances();
            $studentAttendance = $attendanceModel->StudentAttendanceRecord($userID);
            
            // Get student info from the first record
            $studentInfo = [
                'f_name' => $studentAttendance[0]['Name'] ?? 'N/A',
                'student_id' => $studentAttendance[0]['student_id'] ?? 'N/A'
            ];

            // Create PDF content
            $content = $this->generatePDFContent($studentInfo, $studentAttendance);
            
            // Initialize with proper options
            $html2pdf = new Html2Pdf('P', 'A4', 'en');
            $html2pdf->writeHTML($content);
            $html2pdf->output('attendance_report.pdf', 'D'); // Download the PDF

            //back to previous page
            echo "<script>window.history.back();</script>";
            exit();
        } catch (Html2PdfException $e) {
            echo "PDF Error: " . $e->getMessage();
            echo "<script>setTimeout(function(){ window.history.back(); }, 3000);</script>";
        } catch (\Exception $e) {
            echo "General Error: " . $e->getMessage();
            echo "<script>setTimeout(function(){ window.history.back(); }, 3000);</script>";
        }
    }

    private function generatePDFContent($studentInfo, $attendanceRecord)
    {
        $content = '
        <style>
            .header { text-align: center; color: #a31d1d; margin-bottom: 20px; }
            .student-info { margin-bottom: 20px; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th { background-color: #f3f4f6; color: #a31d1d; text-align: left; padding: 10px; }
            td { padding: 10px; border-bottom: 1px solid #e5e7eb; }
            .footer { text-align: center; font-size: 12px; color: #666; }
        </style>
        
        <div class="header">
            <h1>Attendance Report</h1>
            <h2>University of Southeastern Philippines</h2>
        </div>
        
        <div class="student-info">
            <p><strong>Student Name:</strong> ' . htmlspecialchars($studentInfo['f_name']) . '</p>
            <p><strong>Student ID:</strong> ' . htmlspecialchars($studentInfo['student_id']) . '</p>
            <p><strong>Generated Date:</strong> ' . date('F j, Y') . '</p>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Date</th>
                    <th>Time In</th>
                    <th>Time Out</th>
                </tr>
            </thead>
            <tbody>';

        if (!empty($attendanceRecord)) {
            foreach ($attendanceRecord as $record) {
                $content .= '<tr>
                    <td>' . htmlspecialchars($record['event_name']) . '</td>
                    <td>' . date('M j, Y', strtotime($record['atten_started'])) . '</td>
                    <td>' . $record['time_in'] . '</td>
                    <td>' . ($record['time_out'] ?: 'Not yet recorded') . '</td>
                </tr>';
            }
        } else {
            $content .= '<tr><td colspan="4" style="text-align: center;">No attendance records found.</td></tr>';
        }

        $content .= '</tbody></table>
        
        <div class="footer">
            <p>This is an official document generated by the USeP QR Code Attendance System</p>
            <p>Generated on: ' . date('F j, Y g:i A') . '</p>
        </div>';

        return $content;
    }
}

$pdfGeneration = new PDFgeneration();
$pdfGeneration->generatePDF();
